### ISSUE TITLE
Faster TFHE Bootstrapping by Block Binary Keys

### ISSUE THREAD

**Issue by gogo9th** [zama-ai/tfhe-rs#1011]
## Feature request
I wonder if this paper's technique has been applied to tfhe-rs:

[Faster TFHE Bootstrapping with Block Binary Keys](https://eprint.iacr.org/2023/958)

## Motivation
The paper reports that this technique can reduce the bootstrapping time by almost half.

**Comment by IceTDrinker** [comment]
hello @gogo9th we are looking into it and are not yet sure whether it will be useful or not

if you know of implementations we can benchmark to check the performance gains let us know !
