### ISSUE TITLE
How to Use the `private_functional_packing_keyswitch_key` Function in TFHE-rs

### ISSUE THREAD

**Issue by swanhong** [zama-ai/tfhe-rs#105]
Hi,

I am currently attempting to use the packing algorithm in order to pack various LWE ciphertexts into one RLWE (or GLWE) ciphertext. I believe that the `private_functional_packing_keyswitch_key` function is related to this subject and that it is based on algorithm 2 in [[CGGI20](https://eprint.iacr.org/2017/430.pdf)]. However, unlike other functions, I have not been able to find any explanation or test documentation for this function in the code, such as in `lwe_private_functional_packing_keyswitch_key_generation.rs`.

Could you please provide an example code for using this function, or recommend other options for packing multiple ciphertexts? Additionally, do you have any plans to implement a public key version of this function as well?

**Comment by IceTDrinker** [comment]
Hello,

Yes this function was one of the later additions to the code base and is not documented as well as others, I’ll take sometime tomorrow (EU timezone) to try and answer more precisely to your question.

What do you mean by a public key version ?

Cheers

**Comment by swanhong** [comment]
Thanks! I'll wait for your answer. 

For public key version, I meant the public key switching algorithm as described in Algorithm 1 in [CGGI20]. Currently I understand that the `private_functional_packing_keyswitch_key` function is specifically for private key switching as its name. Correct me if I'm wrong.

**Comment by IceTDrinker** [comment]
Alright so for the question about the public vs private functional packing keyswitch:

in the public case the function is known by the machine/party performing the computation and therefore the ai coefficients from algorithm 1 are computed just in time

for the private case, a precomputation happens and the result of those pre-computations are encrypted in the keyswitching key KS^(f), meaning that the functional evaluation in that case is private, as the machine/party performing the computation is not able to see the values that were pre-computing, effectively making f private

As for usage here is a snippet where we pack LWEs and multiply them by 2 via a private function encrypted in the keyswitch key:

```rust
use tfhe::core_crypto::prelude::*;

pub fn main() {
    // DISCLAIMER: these toy example parameters are not guaranteed to be secure or yield correct
    // computations
    let lwe_dimension = LweDimension(769);
    let glwe_dimension = GlweDimension(1);
    let polynomial_size = PolynomialSize(2048);
    let lwe_modular_std_dev = StandardDev(0.0000043131554647504185);
    let pfks_level = DecompositionLevelCount(2);
    let pfks_base_log = DecompositionBaseLog(15);
    let pfks_modular_std_dev = StandardDev(0.00000000000000029403601535432533);

    let mut seeder = new_seeder();
    let mut encryption_random_generator =
        EncryptionRandomGenerator::<ActivatedRandomGenerator>::new(seeder.seed(), seeder.as_mut());
    let mut secret_random_generator =
        SecretRandomGenerator::<ActivatedRandomGenerator>::new(seeder.seed());

    let lwe_sk = allocate_and_generate_new_binary_lwe_secret_key(
        lwe_dimension,
        &mut secret_random_generator,
    );

    let glwe_sk = allocate_and_generate_new_binary_glwe_secret_key(
        glwe_dimension,
        polynomial_size,
        &mut secret_random_generator,
    );

    // Encoding
    let delta = 1 << 60;
    let message_modulus = 1 << 4;

    // We will only pack all possible messages once so here 16 in total
    // Create the plaintext list with the right encoding
    let plaintext_list = PlaintextList::from_container(
        (0..message_modulus)
            .map(|x| x * delta)
            .collect::<Vec<u64>>(),
    );

    let mut lwe_ciphertext_list = LweCiphertextList::new(
        0,
        lwe_dimension.to_lwe_size(),
        LweCiphertextCount(plaintext_list.plaintext_count().0),
    );

    // Encrypt our plaintexts that encode 0 to 15 included
    encrypt_lwe_ciphertext_list(
        &lwe_sk,
        &mut lwe_ciphertext_list,
        &plaintext_list,
        lwe_modular_std_dev,
        &mut encryption_random_generator,
    );

    let mut pfpksk = LwePrivateFunctionalPackingKeyswitchKey::new(
        0,
        pfks_base_log,
        pfks_level,
        lwe_dimension,
        glwe_dimension.to_glwe_size(),
        polynomial_size,
    );

    // Here there is some freedom for the choice of the last polynomial from algorithm 2
    // By convention from the paper the polynomial we use here is the constant -1
    let mut last_polynomial = Polynomial::new(0, polynomial_size);
    // Set the constant term to u64::MAX == -1i64
    last_polynomial[0] = u64::MAX;

    // Generate the LWE private functional packing keyswitch key
    par_generate_lwe_private_functional_packing_keyswitch_key(
        &lwe_sk,
        &glwe_sk,
        &mut pfpksk,
        pfks_modular_std_dev,
        &mut encryption_random_generator,
        |x| (2 * x),
        &last_polynomial,
    );

    // Prepare our output GLWE in which we pack our LWEs
    let mut output_glwe = GlweCiphertext::new(0, glwe_dimension.to_glwe_size(), polynomial_size);

    // Keyswitch and pack
    private_functional_keyswitch_lwe_ciphertext_list_and_pack_in_glwe_ciphertext(
        &pfpksk,
        &mut output_glwe,
        &lwe_ciphertext_list,
    );

    let mut output_plaintext = PlaintextList::new(0, PlaintextCount(polynomial_size.0));

    decrypt_glwe_ciphertext(&glwe_sk, &output_glwe, &mut output_plaintext);

    // To round our 4 bits of message
    let decomposer = SignedDecomposer::new(DecompositionBaseLog(4), DecompositionLevelCount(1));

    // In the paper we return the complicated sum times -1, so here we invert that -1, otherwise we
    // could apply the wrapping_neg on our function and remove it here
    let decoded: Vec<_> = output_plaintext
        .iter()
        .map(|x| (decomposer.closest_representable(*x.0) / delta).wrapping_neg() % message_modulus)
        .collect();

    // First 16 cells will contain the double of the original message modulo our message modulus and
    // zeros elsewhere
    println!("{decoded:?}");
}
```

outputs (shortened):

```console
[0, 2, 4, 6, 8, 10, 12, 14, 0, 2, 4, 6, 8, 10, 12, 14, 0, 0, 0, 0, ... 0]
```

So the 16 first cells do contain the double of the original message, try playing around with the function we use while keeping it R-lipsichitzian and you should be able to output different values, not sure how to select parameters to manage noise

**Comment by swanhong** [comment]
Thanks for the helpful example!

I have one more question about the `last_polynomial` variable in the keyswitch function. While I can easily understand how the input function (e.g. `|x| 2*x`) affects the output of the algorithm, I'm not clear on how `last_polynomial` comes into play. Can you explain how this variable fits into the algorithm described in the [CGGI20] paper?

**Comment by IceTDrinker** [comment]
The last polynomial is the gothic k_{n+1} from algorithm 2 of the CGGI20 paper I believe

**Comment by swanhong** [comment]
Got it! I appreciate your effort in addressing my questions. I will close this issue.
