### ISSUE TITLE
Buffer issue in 'generate_lwe_private_functional_packing_keyswitch_key'

### ISSUE THREAD

**Issue by smilecjf** [zama-ai/tfhe-rs#108]
**Describe the bug**
`LwePrivateFunctionalPackingKeyswitchKeyList` object generated by `allocate_and_generate_new_circuit_bootstrap_lwe_pfpksk_list` seems to be incorrect, while that generated by `par_allocate_and_generate_new_circuit_bootstrap_lwe_pfpksk_list` works well.

**To Reproduce**
1. For `new_wopbs_key_only_for_wopbs` function in `shortint\engine\wopbs\mod.rs`, change `par_allocate_and_generate_new_circuit_bootstrap_lwe_pfpksk_list` function into `allocate_and_generate_new_circuit_bootstrap_lwe_pfpksk_list`.
2. Run the example code of `generate_lut_without_padding` function several times.

**Expected behaviour**
The assertion condition `assert_eq!(res, (m * m) % message_modulus)` fails.

**Evidence**
When `new_wopbs_key_only_for_wopbs` uses `par_allocate_asnd_generate_new_circuit_bootstrap_lwe_pfpksk_list`, the test passes.
![par_allocate](https://user-images.githubusercontent.com/22416402/220326207-1d95f443-5e06-4c01-a47b-f11bd179358a.PNG)

However, when it is changed into `allocate_and_generate_new_circuit_bootstrap_lwe_pfpksk_list`, the test fails.
![allocate_error](https://user-images.githubusercontent.com/22416402/220326641-8a710df3-2fe4-40b3-b52c-796811601a46.PNG)

**Configuration(please complete the following information):**
 - OS: Ubuntu 22.04
 - CPU: AMD Ryzen 7 2700X

**Additional context**
I think the problem comes from the buffer variable `messages` is not reset in the last loop of `generate_lwe_private_functional_packing_keyswitch_key` function. In the case of `par_generate_lwe_private_functional_packing_keyswitch_key`, the variable is declared inside the loop, so that it is always filled with zero in every iteration. I found that this issue is fixed after declaring the buffer variable inside the last loop of `generate_lwe_private_functional_packing_keyswitch_key`.
![allocate_fix](https://user-images.githubusercontent.com/22416402/220327792-fb2ba832-0e13-4c13-a2dc-89b8331882ad.PNG)

**Comment by IceTDrinker** [comment]
Thanks a lot ! Will look to fix this ASAP

**Comment by IceTDrinker** [comment]
Thanks a lot for the very detailed bug report @smilecjf !

I was able to confirm that the serial generation and parallel generation were different (the serial one being plain wrong because of the missed buffer reset), as we now mostly use parallel generation for speed reasons we had a lack of coverage on that part of the code.

I'll open a PR which checks for keygen equivalence between both versions.
