### ISSUE TITLE
(G)lweCiphertextList::from_fn methods

### ISSUE THREAD

**Issue by leonardohn** [zama-ai/tfhe-rs#1108]
**What is the problem you want to solve and can not with the current version?**
There is no straightforward way of arbitrarily initializing (G)lweCiphertextList structs.

**Describe the solution you'd like**
Implement methods named (G)lweCiphertextList::from_fn, that instead of receiving a fixed initialization value for the whole list, receives a closure with an usize parameter (the index) and returns the plaintext initialization value, so the user is able to initialize and encrypt the list arbitrarily, similar to [std::array::from_fn](https://doc.rust-lang.org/std/array/fn.from_fn.html) methods.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by IceTDrinker** [comment]
hello @leonardohn that's a very good suggestion indeed, thanks :)

**Comment by IceTDrinker** [comment]
We don't have much bandwidth additional on our end so if you want to contribute you are welcome to do so by the way

**Comment by leonardohn** [comment]
Hi! Thanks for the encouragement! I sent a PR addressing this issue, could you please review?
