### ISSUE TITLE
Unexpected result from keyswitch_programmable_bootstrap_bivariate

### ISSUE THREAD

**Issue by okuyiga** [zama-ai/tfhe-rs#115]
**To Reproduce**
https://gist.github.com/okuyiga/a8528d96a500ef079f98245cfad7876e

**Expected behaviour**
`is_functional_bivariate_pbs_possible` should provide reliable data on when `keyswitch_programmable_bootstrap_bivariate` can be safely used

**Evidence**
See snippet for reproduction

**Comment by IceTDrinker** [comment]
Thanks for the report, we'll be checking this on our end, but it seems that there is something a bit odd going on indeed

**Comment by IceTDrinker** [comment]
this should have been closed by https://github.com/zama-ai/tfhe-rs/pull/141 if you are still experiencing issues don't hesitate to open a new issue 🙂
