### ISSUE TITLE
Documentation error in `message_extract`

### ISSUE THREAD

**Issue by kc1212** [zama-ai/tfhe-rs#132]
In the documentation of `message_extract` https://docs.rs/tfhe/latest/tfhe/shortint/server_key/struct.ServerKey.html#method.message_extract

There's a mismatch between the comments and the parameter `PARAM_MESSAGE_1_CARRY_1`. 

I think the parameter should be updated to `PARAM_MESSAGE_2_CARRY_2` or change the comment to show a single bit.

**Comment by IceTDrinker** [comment]
Indeed, 2_2 seems more reasonable, thanks !
