### ISSUE TITLE
Cuda compiling Error

### ISSUE THREAD

**Issue by wyunhao** [zama-ai/tfhe-rs#1327]
Hi there,

I am trying to write some code inside your library for personal testing and benchmarks, and thus cloned the whole repo and tried to build it. I installed rust and cuda following this [link](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_network), with GCP n2 (1 GPU).
However, when I run  `cargo run --release`, it said 
```
CMake Error at CMakeLists.txt 15:
    Cuda compiler not found.
```

Could you please provide some instructions on installing and compiling the whole repo?
Great thanks!

**Comment by IceTDrinker** [comment]
Hello @wyunhao 

did you perform the post installation steps ?

https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#post-installation-actions

**Comment by IceTDrinker** [comment]
hello @wyunhao did the previous answer solve your issue ?

**Comment by wyunhao** [comment]
Hi @IceTDrinker, thank you for the information. I also executed the [mandatory post-installation actions](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#mandatory-actions), but still the error `Cuda compiler not found`. Any clues on this?

**Comment by IceTDrinker** [comment]
What does

which nvcc

output ?

**Comment by wyunhao** [comment]
`which nvcc` gives me: `/usr/local/cuda-12.5/bin/nvcc`
`nvcc --version`:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Jun__6_02:18:23_PDT_2024
Cuda compilation tools, release 12.5, V12.5.82
Build cuda_12.5.r12.5/compiler.34385749_0
```

The error I got when running `cargo run --release` is like this:
![Screenshot 2024-07-12 at 10 49 12 PM](https://github.com/user-attachments/assets/6ce47eaa-8bc9-44ee-82f5-bd82edcccece)

**Comment by IceTDrinker** [comment]
If you run 

cargo build -p tfhe-cuda-backend

Can you share the error log you get ?

**Comment by IceTDrinker** [comment]
Also can you share the linux distribution you use please with version ?

**Comment by IceTDrinker** [comment]
@wyunhao I'm going to close this issue having not heard back.

If you still encounter problems please re-open this issue and we are going to need more details, as here it's hard to tell what's happening
