### ISSUE TITLE
run tfhe-rs in macos m1 aarch64

### ISSUE THREAD

**Issue by Miaowwwwwww** [zama-ai/tfhe-rs#136]
**Describe the bug**
run tfhe-rs in macos aarch64 

**Evidence**
error: failed to select a version for `tfhe`.
    ... required by package `tfhetest v0.1.0 (/Users/miao/Documents/Miao/2021 MA/rust_projects/tfhetest)`
versions that meet the requirements `*` are: 0.1.10, 0.1.9, 0.1.8, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.0.0

the package `tfhetest` depends on `tfhe`, with features: `aarch64-unix` but `tfhe` does not have these features.

failed to select a version for `tfhe` which could resolve this conflict
<img width="759" alt="image" src="https://user-images.githubusercontent.com/57083919/224458506-358ba388-9458-4671-b77e-882c84f8f768.png">

**Configuration(please complete the following information):**
 - OS: macos m1

**Comment by IceTDrinker** [comment]
Can you share the Cargo.toml from your project ? Also if you have a workspace the Cargo.toml from the workspace as well

**Comment by Miaowwwwwww** [comment]
您好，我是苗炜捷，您的邮件我已经收到，我会在详尽阅读后尽快给您答复，谢谢！

**Comment by Miaowwwwwww** [comment]
Hi,When I fixed the version to 0.1.10, the error became as follows:
<img width="867" alt="image" src="https://user-images.githubusercontent.com/57083919/224474622-ac76e2f9-adf6-4a76-84b8-99a89dbe25b2.png">
<img width="867" alt="image" src="https://user-images.githubusercontent.com/57083919/224474638-3bc3aece-f673-4b6a-829f-714c4ed05232.png">

**Comment by Miaowwwwwww** [comment]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/57083919/224475809-698cb348-854f-4789-96ce-b00841a43bb6.png">
Hi , I tried to change the code to: tfhe = { version = "0.1.10", features = [ "aarch64-unix"] } That is, I deleted the first three elements and got the error shown in the figure

**Comment by Miaowwwwwww** [comment]
Finally, I tried to change the code to: tfhe = { version = "*", features = [ "boolean", "shortint", "aarch64-unix"] } That is, the "integer" element is deleted, and you can run tfhe-rs github There are two examples provided in the documentation (a full example evaluating a Boolean circuit and example of how the library can be used with shortints), but I'm still confused.

In addition, I cloned tfhe-rs to the local tfhe-rs directory for execution, executed cargo build --release and cargo test operations, and got the following error during cargo test:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/57083919/224477317-e0d3c6c7-f081-40b4-af56-2bd11922a2d1.png">
<img width="702" alt="image" src="https://user-images.githubusercontent.com/57083919/224477325-c2309d53-2951-4732-9363-569e5285eaca.png">
<img width="712" alt="image" src="https://user-images.githubusercontent.com/57083919/224477338-6ee73cf4-1f5f-4e24-bb1f-883b5ce9f3c1.png">

**Comment by IceTDrinker** [comment]
`tfhe::encryption` is not a thing, can you indicate where you found the code in question ?

Also integer is not available in tfhe 0.1.10 it will be for the next 0.2.0 release that is in preparation

The issues you are seeing in tests however are very weird

**Comment by IceTDrinker** [comment]
Official doc for the released TFHE-rs 0.1 is available here https://docs.zama.ai/tfhe-rs

**Comment by tmontaigu** [comment]
Both errors are due to overflows being caught as the tests are being run in debug mode.

If you run the tests with the `--release`  flag they should work as the value will safely wrap-around as it is intended)

On our end we could use explicit `wrapping_` operations
