### ISSUE TITLE
[BUILD] fix arguments for wasm-pack build targets in Makefile

### ISSUE THREAD

**Issue by rdlopes** [zama-ai/tfhe-rs#143]
**Describe the bug**
One cannot build wasm bindingd for JS and Node using Makefile build targets.

**To Reproduce**
Steps to reproduce the behaviour
1. clone the repo
2. run a make target for WASM bindgen

**Expected behaviour**
- build should execute with no errors and 
- wasm file should be present in `tfhe-rs/tfhe/pkg`

**Evidence**
This is the error we get from the command line
```sh
/usr/bin/make -f /Users/rdlopes/Developer/rdlopes/tfhe-rs/Makefile -C /Users/rdlopes/Developer/rdlopes/tfhe-rs build_node_js_api
cd tfhe && \
	RUSTFLAGS="" rustup run "stable" \
		wasm-pack build --release --target=nodejs \
		--features=boolean-client-js-wasm-api,shortint-client-js-wasm-api
error: Found argument '--features' which wasn't expected, or isn't valid in this context

USAGE:
    wasm-pack build --release --target <target>

For more information try --help
make: *** [build_node_js_api] Error 1

Process finished with exit code 2
```

**Configuration(please complete the following information):**
 - OS: Mac OSX (x86 intel)

**Comment by rdlopes** [comment]
The solution is to pass the arguments to the wasm-pack command itself by adding `--` before `--features` flag.

For the aforementioned make target, that would be:
```
.PHONY: build_node_js_api # Build the js API targeting nodejs
build_node_js_api: install_rs_build_toolchain
	cd tfhe && \
	RUSTFLAGS="$(WASM_RUSTFLAGS)" rustup run "$(RS_BUILD_TOOLCHAIN)" \
		wasm-pack build --release --target=nodejs \
		-- --features=boolean-client-js-wasm-api,shortint-client-js-wasm-api
```

**Comment by IceTDrinker** [comment]
Thanks for the bug report, let us check on our end, if you want to contribute you will need to sign a CLA (I'll get back to you with the relevant information)

**Comment by IceTDrinker** [comment]
can you share your wasm-pack version please ?

```
wasm-pack --version
```

**Comment by IceTDrinker** [comment]
Fixed by https://github.com/zama-ai/tfhe-rs/pull/144
