### ISSUE TITLE
Add rotation (left/right) operation to integer digits

### ISSUE THREAD

**Issue by rdlopes** [zama-ai/tfhe-rs#145]
**What is the problem you want to solve and can not with the current version?**
At the moment, no rotate (left/right) operation is available for the shortint/integer digits.

**Describe the solution you'd like**
Adding to the shortint/integers API two methods:
- rotate_left
- rotate_right

**Describe alternatives you've considered**
Only manual implementation can offer an alternative at the moment.

**Comment by IceTDrinker** [comment]
Hello @rdlopes do you mean a shift operation ?

Like:

```
0b1100 >> 2 == 0b0011
```

?

**Comment by rdlopes** [comment]
Hi @IceTDrinker, no, I mean a rotation operation.

Like:
```
rotate_left(0b1001001, 1) == 0b0010011
rotate_right(0b1001001, 2) == 0b0100110
```

**Comment by IceTDrinker** [comment]
ok understood, indeed it's not something we have at the moment, it should be doable at the shortint level using https://docs.rs/tfhe/0.1.11/tfhe/shortint/server_key/struct.ServerKey.html#method.keyswitch_programmable_bootstrap and a well crafted accumulator

**Comment by IceTDrinker** [comment]
yep thanks for the feedback ! If you have something to contribute we are open source :)

**Comment by dragan2234** [comment]
writing left(and right) rotation using high level api is as easy as:
```
(ct << 2u32) | (ct >> 30u32);
```
This example is for 32bit number

**Comment by dragan2234** [comment]
Actually, I'm not sure if the implementation above works for all cases, but here's the one that it works 100%:
```
fn rotate_right(x: FheUint32, amount: u32) -> FheUint32 {
    let mut x_ = x.clone();
    let other = 32u32 - amount;
    let first: FheUint32 = x.clone() << other;

    x_.shr_assign(amount);

    let res = first.clone() + x_.clone();

    res
}
```

**Comment by IceTDrinker** [comment]
thanks ! we'll see what we want to do with it 🙂

**Comment by dragan2234** [comment]
@IceTDrinker as discussed in discord, it seems you have fixed this with this PR: https://github.com/zama-ai/tfhe-rs/pull/228

So [this comment](https://github.com/zama-ai/tfhe-rs/issues/145#issuecomment-1517971136) is fine, I have tested it again with `0.2.3` version

**Comment by IceTDrinker** [comment]
We have a specific rotation operation coming I believe but good thing it was fixed then !
