### ISSUE TITLE
error: failed to run custom build command for `tfhe-cuda-backend v0.3.0 (/mnt/d/work/research/tfhe-rs/backends/tfhe-cuda-backend)`

### ISSUE THREAD

**Issue by shangsony** [zama-ai/tfhe-rs#1478]
**Describe the bug**
error: failed to run custom build command for `tfhe-cuda-backend v0.3.0 (/mnt/d/work/research/tfhe-rs/backends/tfhe-cuda-backend)`

Caused by:
  process didn't exit successfully: `/mnt/d/work/research/tfhe-rs/target/debug/build/tfhe-cuda-backend-214a75f592ffd7a9/build-script-build` (exit status: 101)
  --- stdout
  Build tfhe-cuda-backend
  cargo::rerun-if-changed=cuda/include
  cargo::rerun-if-changed=cuda/src
  cargo::rerun-if-changed=cuda/tests_and_benchmarks
  cargo::rerun-if-changed=cuda/CMakeLists.txt
  cargo::rerun-if-changed=src
  cargo:warning=This Linux distribution is not officially supported. Only Ubuntu is supported by tfhe-cuda-backend at this time. Build may fail

  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/mnt/d/work/research/tfhe-rs/target/debug/build/tfhe-cuda-backend-8cf40089eb188e53/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/mnt/d/work/research/tfhe-rs/backends/tfhe-cuda-backend/cuda" "-DCMAKE_INSTALL_PREFIX=/mnt/d/work/research/tfhe-rs/target/debug/build/tfhe-cuda-backend-8cf40089eb188e53/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  -- Configuring incomplete, errors occurred!

  --- stderr
  CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
    CMake 3.24 or higher is required.  You are running version 3.16.3

  thread 'main' panicked at /home/sonyshang/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 1
**To Reproduce**
Steps to reproduce the behaviour
1. first step
2. second step
3. etc

**Expected behaviour**

**Evidence**
If applicable, add material to help explain your problem (e.g. screenshots, logs, artifacts, etc.).

**Configuration(please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]

**Additional context**

**Comment by IceTDrinker** [comment]
@shangsony your version of cmake is too old see the error log

> --- stderr
> Error at CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.24 or higher is required. You are running version 3.16.3

See https://cmake.org/download/ to install more recent versions.
