### ISSUE TITLE
TFHE vulnerability to full key recovery attacks

### ISSUE THREAD

**Issue by kkaczynski** [zama-ai/tfhe-rs#1490]
**What is the problem you want to solve and can not with the current version?**
I want to know if ZAMA version of TFHE is vulnerable to the key recovery attacks by inducing decryption errors, paper in the context.

**Additional context**
[ePrint paper](https://eprint.iacr.org/2022/1563.pdf)

**Comment by IceTDrinker** [comment]
Hello @kkaczynski

Asked internally about this, the attack relies on a dishonest server and the server having access to the information that a decryption failed, which is similar to what the IND-CPA^D requires to extract the keys (they also need to have a signal about a failed decryption among other things), see the Security Model section https://github.com/zama-ai/tfhe-rs?tab=readme-ov-file#security-model in our readme.

This means that the same counter measure (citing the readme here):

> In particular, it is assumed that the results of decrypted computations are not shared by the secret key owner with any third parties, as such an action can lead to leakage of the secret encryption key.

will thwart the attack.

Hope it answers your question.

**Comment by kkaczynski** [comment]
Thanks @IceTDrinker !
