### ISSUE TITLE
Give original plaintext after decrypting?

### ISSUE THREAD

**Issue by ak26252** [zama-ai/tfhe-rs#164]
**What is the problem you want to solve and can not with the current version?**
I was following the documentation for both tfhe-rs and zama-concrete. When it comes to decrypting the values after operation, zama-concrete is able to fully decrypt the value and give the expected value whereas tfhe-rs is only able to assert if the modulus is correct. I couldn't find anything in the documentation to make tfhe-rs behave similarly to zama-concrete. Is there something in tfhe-rs currently that can support this? Thank you!

**Comment by IceTDrinker** [comment]
Hello @ak26252 

Can you indicate what you are using with a small snippet of code? I'm not sure if you are referring to the rounding made by shortint in TFHE-rs or something else.

Cheers

**Comment by ak26252** [comment]
```
fn main() {
    let (client_key, server_key) = gen_keys(Parameters::default());

    let msg1 = 19;
    let msg2 = 4;

    let modulus = client_key.parameters.message_modulus.0;
    
    let ct_1 = client_key.encrypt(msg1);
    let ct_2 = client_key.encrypt(msg2);
    
    let ct_3 = server_key.checked_add(&ct_1, &ct_2).unwrap();
    let output = client_key.decrypt(&ct_3);

    assert_eq!(output, (msg1 + msg2) % modulus as u64);

    println!("output = {:?}", output);
    println!("msg1 decrypted = {:?}", client_key.decrypt(&ct_1));
}
```

This is the code I'm using. When I run it, the output = 3 and msg1_decrypted = 3 when I was expecting it to be similar to zama-concrete and give me output = 23 and msg1_decrypted = 19. I'm very new to cryptography and haven't had the chance to try to understand TFHE yet so I apologize for that. But I'm assuming this is the intended behavior. Is there any way that I could get the expected outputs with tfhe-rs? Thank you!

**Comment by ak26252** [comment]
Ah sorry this is the primary use statement that I have: `use tfhe::shortint::prelude::*;`

And I see! So then does that mean there's currently no configurations I could do in tfhe-rs to give me the expected output? When can I expect the typed API/frontend? Thank you!

**Comment by IceTDrinker** [comment]
the typed API/frontend is part of the next release cycle so very soon ! stay tuned 🙂

**Comment by ak26252** [comment]
That's exciting thank you! Also, this is more of a conceptual question but I couldn't see a very clear answer on the internet. Is there any scenario where a TFHE ciphertext could be useful? For example someone with lots of ciphertexts performing some sort of data processing. Thanks!

**Comment by IceTDrinker** [comment]
I'm not sure I understand your question? What do you mean about the TFHE ciphertext? A compressed one perhaps or packed one?

**Comment by ak26252** [comment]
Ah yes one that's been encoded. Could that be used for anything? And you mention compression/packing. Is there any specific method for compressing/packing ciphertexts that you would recommend?

**Comment by IceTDrinker** [comment]
For the compression we already propose seeded/compressed Ciphertexts for LWE where the public mask is reduced to the seed that allows a CSPRNG to regenerate the mask.

I'm sorry I think I still don't understand your original question about an encoded ciphertext 😅

**Comment by IceTDrinker** [comment]
For a given LweDimension the size of the compressed ciphertext is divided by LweDimension and you add 128 bits for the seed information

**Comment by IceTDrinker** [comment]
hello @ak26252 I will close this issue, don't hesitate to re-open it if needed or ask for support on the FHE.org THFE-rs discord channel: https://discord.com/channels/901152454077452399/1062367401737474058
