### ISSUE TITLE
About Keycache

### ISSUE THREAD

**Issue by pierreeliseeflory** [zama-ai/tfhe-rs#1674]
Hi,

Is the KeyCache structures intended to be used at the application level (as an alternative to the serialization interface) or is just for internal usage ?

If usable by final applications, is it adaptable for the server to hold the server key (and for public encryptors in case of public key) ? From what I understand, by default it holds a SharedKey that contains a ClientKey so it doesn't seem to fit.

Thank you

**Comment by tmontaigu** [comment]
No the keycache is only meant to be used internaly by us for development

**Comment by pierreeliseeflory** [comment]
Ok, thanks
