### ISSUE TITLE
Why do WoPBS LUT generation require ciphertext input?

### ISSUE THREAD

**Issue by danielsjoo** [zama-ai/tfhe-rs#269]
Hello, I was wondering why the LUT generation (generate_lut_radix) for Wopbs requires the ciphertext input when I use the same input for the LUT evaluation. In my code, I am recursively calling a function, and in my head, I imagine that I only need to generate the LUT once to compute on the function (which stays the same) for multiple different inputs. Is there a mathematical reason for this?

To show what I mean, in the example code you provide, you input the ciphertexts twice: one to generate the LUT and one to compute it.
```
let lut = wopbs_key.generate_lut_bivariate_radix(&ct1, &ct2, |x, y| 2 * x * y);
let ct_res = wopbs_key.bivariate_wopbs_with_degree(&ct1, &ct2, &lut);
```

**Comment by IceTDrinker** [comment]
Hello @danielsjoo it has to do with how carries are managed inside radix integer ciphertexts, passing the ciphertexts allows to encode the table without necessarily having to clean the carries before running the wopbs, as the carry propagation is currently a linear operation in the number of blocks in the ciphertext and so means paying a fixed amount of time which may sometimes be absorbed by crafting the wopbs table carefully for "dirty" carries

**Comment by IceTDrinker** [comment]
@danielsjoo I will close this issue, if you think the answer is lacking information feel free to re-open it.

Cheers
