### ISSUE TITLE
Not able to run benchmark on GCP

### ISSUE THREAD

**Issue by wyunhao** [zama-ai/tfhe-rs#292]
Hi there,

I was trying to reproduce the benchmark result on a GCP instance (with Ubuntu 20.04 x86-64 boot disk).
After the installation steps, I ran `cargo bench` and got the following error message:

`thread 'main' panicked at 'Unable to instantiate a seeder, make sure to enable a seeder feature like seeder_unix for example on unix platforms.', tfhe/src/core_crypto/seeders.rs:122:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

Could you please provide any insights on how to work this around?

Great thanks!

**Comment by wyunhao** [comment]
It takes out that pass in `seeder_unix` to features in the command (e.g., `cargo bench --features="boolean internal-keycache","seeder_unix" --bench boolean-bench`) would do the job. This trick is included in the tfhe/src/core_crypto/seeders.rs file's comment block.

**Comment by IceTDrinker** [comment]
For x86_64 machines you can use the feature `x86_64` which will enable the rdseed seeder from the CPU and the efficient CSPRNG, you can also use `x86_64-unix` to use /dev/random as a fallback.

On arm based platforms you can use `aarch64`, `aarch64-unix`
