### ISSUE TITLE
Best way to add a plaintext argument for PBS functions

### ISSUE THREAD

**Issue by cgouert** [zama-ai/tfhe-rs#318]
I would like to pass an additional argument to a function that will get converted to a LUT for PBS. Ideally, I want something like this: 

```rust
fn foo(x: u64, my_vec: &Vec<u64>) -> u64 {
    my_vec[x as usize]
}
```

For radix ciphertexts, it was straightforward to modify the `generate_lut_radix` function to support input functions that take in an additional argument. However, it seems that modifying the `generate_accumulator` function will not be so straightforward since the call chain is fairly deep. I noticed that there are bivariate versions of the `generate_accumulator` function, but these seem to take in an additional ciphertext. Is there an easier way to do this?

cc @jimouris

**Comment by tmontaigu** [comment]
Have you tried closures ?

```rust
fn func_with_2_args(a: u64, b: u64) -> u64 {
    a + b
}

fn main() {
    let b= 10;
    let func_with_one_arg = |x| func_with_2_args(x, b);
    
    println!("{}", func_with_one_arg(11));
}
```

**Comment by jimouris** [comment]
Thanks, that did it!
