### ISSUE TITLE
Question: Why are keys so large?

### ISSUE THREAD

**Issue by On0n0k1** [zama-ai/tfhe-rs#391]
I was trying out this crate and implemented the following function for generating and saving keys:

```

/// Will panic if any of the files already exist.
fn create_and_save_keys(client_key_path: &str, server_key_path: &str, public_key_path: &str) {
    // We generate a set of client/server keys, using the default parameters:
    let num_block = 4;
    let (client_key, server_key) = gen_keys_radix(&PARAM_MESSAGE_2_CARRY_2, num_block);
    let public_key = PublicKeyBig::new(&client_key);

    validate_keys(&client_key, &server_key);

    let serialized_client_key = serialize(&client_key).unwrap();
    println!("Client key size (Bytes): {}", serialized_client_key.len());

    let serialized_server_key = serialize(&server_key).unwrap();
    println!("Server key size (Bytes): {}", serialized_server_key.len());

    let serialized_public_key = serialize(&public_key).unwrap();
    println!("Public key size (Bytes): {}", serialized_public_key.len());

    // Save client key
    let mut file = File::create(client_key_path).expect("Failed to create client key file");
    file.write_all(&serialized_client_key)
        .expect("Failed to write to client key file");

    println!(
        "Serialized client key have been saved to '{}'",
        client_key_path
    );

    // Save server key
    let mut file = File::create(server_key_path).expect("Failed to create server key file");
    file.write_all(&serialized_server_key)
        .expect("Failed to write to server key file");

    // Save public key
    let mut file = File::create(public_key_path).expect("Failed to create public key file");
    file.write_all(&serialized_public_key)
        .expect("Failed to write to public key file");

    println!(
        "Serialized server key have been saved to '{}'",
        server_key_path
    );
}

```

This code creates a client key, a server key and a public key. Then serializes them, saving into a local file. The sizes of the keys are as follow:

Client key size (Bytes): 38896
Server key size (Bytes): 109518176
Public key size (Bytes): 2151679680

40KB for a client key, 109MB for a server key, 2 GB for a public key? Why are they so large? Is there some way I can know more about why are they so large? Is there something I can do to reduce the sizes?

One last question. What can we do to optimize the speed for the benchmarks shown in your benchmarks page?

**Comment by On0n0k1** [comment]
the ```serialize``` function I'm using above comes from the "bincode" crate. It will use the Serialize serde crate to the array of bytes.

**Comment by IceTDrinker** [comment]
@On0n0k1 all keys have the expected sizes.

Client key:
- the small LWE KEY for 2_2 params 742 u64
- the big LWE KEY derived from the GLWE KEY (we store it under both forms at the moment) 2048 u64 * 2

This adds up to the size you are seeing.

Server Key contains a Keyswitching Key and a Bootstrapping Key, also with the expected size, this key can be compressed using the CompressedServerKey, size can go down significantly (like / 2 or more).

The public Key is a collections of encryption of 0s in it's non compressed form it's huge, you can reduce the size of that key by about ~2048 using the compressed variant. There are a lot of encryption of 0s to guarantee the security (the maths give a bound on the minimal number of encryption of 0s required.

To optimize the speed of benchmarks : big machine with lots of cores, and you can check the command in the makefile for e.g.

integer_bench: 

make AVX512_SUPPORT=ON bench_integer

which runs

RUSTFLAGS="-C target-cpu=native" cargo +nightly-2023-04-12 bench \
	--bench integer-bench \
	--features=x86_64-unix,integer,internal-keycache,nightly-avx512-p tfhe

Feel free to close the issue if all your questions are answered!

Cheers

**Comment by IceTDrinker** [comment]
Btw @On0n0k1 for the public key we have the so called "CompactPublicKey" coming in the next release, sizes are expected to be in the ~16 kB to 32 kB range for commonly used parameters in shortint !

**Comment by On0n0k1** [comment]
Thank you. This was very helpful.
