### ISSUE TITLE
The `r` resulted from integer `division` when multiplied together always return `0`.

### ISSUE THREAD

**Issue by y-pakorn** [zama-ai/tfhe-rs#410]
**Describe the bug**
The `remainer` or `r` resulted from integer `division` when multiplied together always return `0`.

**To Reproduce**
Steps to reproduce the behaviour

1. Install latest `tfhe`

```toml
tfhe = { git = "https://github.com/zama-ai/tfhe-rs", features = [ "boolean", "shortint", "integer", "internal-keycache"] }
```

2. Encrypt some number with integer radix key
3. Do two division that results in `q` and `r`, In this case `ServerKey::div_rem_parallelized`.
4. Multiply `r` from those division together.
5. The result from that multiplication will always be **zero**.

```rust
fn main() {
    let (client_key, server_key) = IntegerKeyCache.get_from_params(PARAM_MESSAGE_2_CARRY_2);
    const NUM_BLOCK: usize = 4;
    let a: u128 = 248;
    let b: u128 = 249;
    let c: u128 = 250;
    let d: u128 = 251;
    let enc_a = client_key.encrypt_radix(a, NUM_BLOCK);
    let enc_b = client_key.encrypt_radix(b, NUM_BLOCK);
    let enc_c = client_key.encrypt_radix(c, NUM_BLOCK);
    let enc_d = client_key.encrypt_radix(d, NUM_BLOCK);

    let (mut q1, mut r1) = server_key.div_rem_parallelized(&enc_b, &enc_a);
    let (mut q2, mut r2) = server_key.div_rem_parallelized(&enc_d, &enc_c);

    println!("r1: {:?}", client_key.decrypt_radix::<u8>(&r1));
    println!("r2: {:?}", client_key.decrypt_radix::<u8>(&r2));
    println!("q1: {:?}", client_key.decrypt_radix::<u8>(&q1));
    println!("q2: {:?}", client_key.decrypt_radix::<u8>(&q2));

    let r1r2 = server_key.smart_mul_parallelized(&mut r1, &mut r2);
    println!("r1r2: {:?}", client_key.decrypt_radix::<u8>(&r1r2));
    let q1q2 = server_key.smart_mul_parallelized(&mut q1, &mut q2);
    println!("q1q2: {:?}", client_key.decrypt_radix::<u8>(&q1q2));

    let r1_dec = client_key.decrypt_radix::<u8>(&r1);
    let r2_dec = client_key.decrypt_radix::<u8>(&r2);
    let r1_enc = client_key.encrypt_radix(r1_dec, NUM_BLOCK);
    let r2_enc = client_key.encrypt_radix(r2_dec, NUM_BLOCK);

    let r1r2_retry = server_key.mul_parallelized(&r1_enc, &r2_enc);
    println!(
        "r1r2_retry: {:?}",
        client_key.decrypt_radix::<u8>(&r1r2_retry)
    );
}
```

The snippet above will print out
```
r1: 1
r2: 1
q1: 1
q2: 1
r1r2: 0
q1q2: 1
r1r2_retry: 1
```

Notice that `r1r2` will return `0` but `r1r2_retry` that re-encrypt the value will return `1`

**Expected behaviour**
Return actual `r1 * r2`

**Configuration(please complete the following information):**
 - OS: MacOS Monterey 12.6 (21G115)
 - Spec: Macbook M1 Pro w/ 16GB Ram

I've also tried running on @yoyoismee's Macbook Intel laptop but still reproduce the same error.

**Comment by IceTDrinker** [comment]
What happens if you replace the first smart mul by just mul_parallelized ?

**Comment by y-pakorn** [comment]
> What happens if you replace the first smart mul by just mul_parallelized ?

Still output the same value
```
r1: 1
r2: 1
q1: 1
q2: 1
r1r2: 0
q1q2: 1
r1r2_retry: 1
```

**Comment by IceTDrinker** [comment]
Can you try calling full_propagate_parallelized on r1r2 ?

**Comment by IceTDrinker** [comment]
It’s a method of the server key

**Comment by y-pakorn** [comment]
Everything works fine now after fully propagate `r1` and `r2` before multiplication. Thank you! Feel free to close the issue 🫡

```rust
server_key.full_propagate_parallelized(&mut r1);
server_key.full_propagate_parallelized(&mut r2);
```

```
r1: 1
r2: 1
q1: 1
q2: 1
r1r2: 1
q1q2: 1
r1r2_retry: 1
```

**Comment by IceTDrinker** [comment]
We won’t close it right away, it’s a bug on our end, thanks for the report !

**Comment by yoyoismee** [comment]
@IceTDrinker can you explain a bit more about nature of the bug and wether it likely to effect any other functions?

**Comment by IceTDrinker** [comment]
> @IceTDrinker can you explain a bit more about nature of the bug and wether it likely to effect any other functions?

Not quite sure yet, we do some checks on the « fullness » of the shortint ciphertexts in an Integer ciphertext, if we make a wrong decision based on said fullness we may return a wrong result, mul being notoriously costly we have a few checks in place, the full propagation allows to make sure each block contains no carry information and has a « nominal » fullness which allows to be in the classic encrypted setting

**Comment by IceTDrinker** [comment]
We identified the bug, easy fix will be in soon

**Comment by yoyoismee** [comment]
so can we remove all `full_propagate_parallelized` from our code now?

**Comment by IceTDrinker** [comment]
@yoyoismee yes ! It should not have been necessary in the first place, but now we fixed the issue you found, should be good now !
