### ISSUE TITLE
radix Interger scalar_[left/right]_shift rotate if shift more than bit length.

### ISSUE THREAD

**Issue by yoyoismee** [zama-ai/tfhe-rs#415]
**Describe the bug**
given an Integer with bit length `n` (nblock x msg_bit per block). scalar_[left/right]_shift will rotate after `shift > n`

**To Reproduce**
Steps to reproduce the behaviour
1. encode a number to redix
2. call `Serverkey.scalar_right_shift_parallelized` with shift value more than amount of bits in the integer
here's a sample code.
```rust
fn main() {
    let (client_key, server_key) = IntegerKeyCache.get_from_params(PARAM_MESSAGE_2_CARRY_2);
    const NUM_BLOCK: usize = 4;
    let x = 255;
    for i in 0..16 {
        let enc_x = client_key.encrypt_radix(x, NUM_BLOCK);
        let shifted = server_key.scalar_right_shift_parallelized(&enc_x, i);
        println!(
            "{x} - shift {i} - {}",
            client_key.decrypt_radix::<u8>(&shifted),
        )
    }
}
```

**Expected behaviour**

```
255 - shift 0 - 255
255 - shift 1 - 127
255 - shift 2 - 63
255 - shift 3 - 31
255 - shift 4 - 15
255 - shift 5 - 7
255 - shift 6 - 3
255 - shift 7 - 1
255 - shift 8 - 0
255 - shift 9 - 0
255 - shift 10 - 0
255 - shift 11 - 0
255 - shift 12 - 0
255 - shift 13 - 0
255 - shift 14 - 0
255 - shift 15 - 0
```
but we got
```
255 - shift 0 - 255
255 - shift 1 - 127
255 - shift 2 - 63
255 - shift 3 - 31
255 - shift 4 - 15
255 - shift 5 - 7
255 - shift 6 - 3
255 - shift 7 - 1
255 - shift 8 - 255
255 - shift 9 - 127
255 - shift 10 - 63
255 - shift 11 - 31
255 - shift 12 - 15
255 - shift 13 - 7
255 - shift 14 - 3
255 - shift 15 - 1
```

**Configuration(please complete the following information):**
 - OS: `macOS ventura 13.2.1 on M2Pro` 

**Additional context**
while this behavior is unintended it's not really a problem. given that there's no good reason to shift more than n bit since it should be 0 anyway. we accidentally found this from a bug in our code that we shift more then we need to.

**Comment by IceTDrinker** [comment]
It's not actually a bug it's the behavior of rust on shifts with overflows

https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=76e82fe38076ec2e22a5aef41fd19be8

**Comment by tmontaigu** [comment]
Yes, this is the intended behaviour, we are matching rust

**Comment by yoyoismee** [comment]
ok sgtm.
