### ISSUE TITLE
How to turn on GPU support

### ISSUE THREAD

**Issue by KaneX** [zama-ai/tfhe-rs#420]
I read on your web page that concrete supports GPU acceleration. ("Optional GPU acceleration makes things even faster." on https://zama.ai/concrete/)

The question is that how can we turn on GPU support? I have searched through this repo and the document, but didn't find any clue about GPU. Could you provide a benchmark on the speedup of GPU acceleration?

**Comment by jborfila** [comment]
See issue #237 also related to GPU :)
