### ISSUE TITLE
Applying bootstrap to VectorLWE

### ISSUE THREAD

**Issue by SpiralEndlessly** [zama-ai/tfhe-rs#421]
I am working on implementing the forward pass of a neural network homomorphically encrypted using Concrete. For bootstrapping I am currently looping over the VectorLWE and applying bootstrap_nth for each encrypted value separately. This would look significantly cleaner code-wise if there was a method to apply the (functional) Bootstrap to the entire VectorLWE at once.

Would it be possible to have an analogue to the LWE bootstrap and bootstrap_with_function methods that operate on an entire VectorLWE in a future release?

**Comment by IceTDrinker** [comment]
hello @SpiralEndlessly this is issue was transferred to this repo as we have re-organized our products. I know the issue is a bit ancient but is it something you still need ?

**Comment by SpiralEndlessly** [comment]
I'm no longer involved in the FHE space, so I am not familiar with the current iteration of Concrete/tfhe-rs. If the library API is still similar as it was then (no method to apply batched bootstraps with identical parameters to many LWE) this could be considered a small QOL improvement, but otherwise feel free to close.

**Comment by IceTDrinker** [comment]
There are ways to do it though it's not a primitive in itself. we also have a more recent issue for it #31 

I'll be closing.

Thanks for your answer and all the best !
