### ISSUE TITLE
Execute TFHE Encrypted WASM?

### ISSUE THREAD

**Issue by manglemix** [zama-ai/tfhe-rs#422]
**What is the problem you want to solve and can not with the current version?**
This isn't really an issue I have, but I am curious, is it possible (or been attempted) to create an executor for encrypted WASM. My guess is that the stack and heap would be encrypted, but there could be some pipe that allows the binary to message to some outer process some arbitrary plaintext instructions.

**Describe the solution you'd like**
For example, using a Model View Controller, the Model would be compiled to an encrypted binary, and the actual program will be a conventionally compiled binary which includes the executor. Data can be piped into the executing wasm, from the controller and data can be returned from it with instructions to the view. That way, graphics can still be handled quickly without this, but core functionality will remain hidden.

**Describe alternatives you've considered**
I have not been able to find any alternatives, but please let me know if you've found any

**Comment by IceTDrinker** [comment]
hello @manglemix our projects have been re-organized so this issue was migrated to this repo !

We don't currently have support for the crypto operations for the WASM target, for now it is not on our roadmap for your information.

Cheers

**Comment by IceTDrinker** [comment]
hello @manglemix it looks like this question was more a theoretical question of "could this sort of thing be done"

It looks to me that with the high level API one could reasonably try to implement a sort of oblivious CPU/interpreter, meaning that encrypted wasm could likely be achieved, I do not believe it is something TFHE-rs would implement itself, so I will be closing this issue.

If you think this issue should not have been closed then please let us know.

For other questions don't hesitate to open new issues.

Cheers
