### ISSUE TITLE
editing subprojects locally

### ISSUE THREAD

**Issue by lattice0** [zama-ai/tfhe-rs#424]
Hello, it looks like this repo contains copies of the subrepos (concrete, conrete-core, concrete-bool, etc) with different versions each, so when you clone everything and point each dependency to its local version, it simply won't work. Shouldn't you be using git submodules and keep each cargo subproject in a different repo, so you point each to the exact commit where everything works together? How are you guys doing local modifications?

**Comment by IceTDrinker** [comment]
hello @lattice0 this issue was formerly in the concrete repository, as our projects have been re-organized we don't have the dependencies in the workspace anymore so I'm going to close this issue, if you have other problems or feel like the problem is not solved feel free to open a new issue 🙂
