### ISSUE TITLE
Help wanted: look into a table homomorphically with concrete

### ISSUE THREAD

**Issue by Megaloblastt** [zama-ai/tfhe-rs#425]
Hello to Zama/Concrete team, and thanks for allowing us to mimic a fraction of TFHE power.

**What is the problem you want to solve and can not with the current version?**
I'm actually trying to implement an AES using `concrete`. Since AES can be reduced as exclusively XOR and look-ups, I have the felling that the function-bootsrapping feature of TFHE fits perfectly this use case. I've tried different ways to achieve this goal using almost all of the bootstrapping functions available in `concrete/concrete-core` but was not able to get accurate results. I have the feeling that something is wrong with my choice of parameters, but all those I tried led to miserable failures...

**Describe the solution you'd like**
I would like to understand what's wrong with my choice of parameters, or if it's even possible with concrete, and how.

**Describe alternatives you've considered**
I already implemented a working version (albeit slow) of it using a bit-wise approach, where each bit is encrypted individually using the `concrete-boolean` package, and lookups are implemented using a network of CMUX gates. It works, but is slow as hell...

**Additional context**
I'm attaching my latest code (as a TXT file, since GitHub does not let me import .rs files) trying to make it work (NB: I tried with both different and same LWE/RLWE key, neither worked)
[main.txt](https://github.com/zama-ai/concrete/files/8633408/main.txt)

**Comment by IceTDrinker** [comment]
Hello @Megaloblastt this is issue was transferred from the concrete repository to this one following the re-organization of our products.

If the issue is still of interest to you may be able to use the HL API or shortint/integer APIs to implement an homomorphic AES.

See : https://docs.zama.ai/tfhe-rs/high-level-api/tutorial

**Comment by IceTDrinker** [comment]
hello @Megaloblastt as this issue is pretty old and not relevant wrt the newer versions of TFHE-rs I'll close it at the end of the week if there is no more activity on it, if necessary you can open a new issue if it is still relevant to you 🙂 

Cheers

**Comment by IceTDrinker** [comment]
hello @Megaloblastt closing, if you think this issue should not have been closed feel free to re-open it.

If you have different questions/support requests feel free to open new issues.

Cheers!
