### ISSUE TITLE
TFHE-rs for Web Assembly

### ISSUE THREAD

**Issue by patriciaOrtuno28** [zama-ai/tfhe-rs#427]
Hi! 
I'm opening this issue to ask about the progress of the migration of Concrete's libraries to Web Assembly. I intend to use it with wasm-bindgen, but, at the moment, Concrete only supports x86_64 arch from what I've seen.
Thank you in advance.

**Comment by IceTDrinker** [comment]
this is issue is ancient and the question has resurfaced here https://github.com/zama-ai/tfhe-rs/issues/1034

Closing this issue in favor of the more recent one
