### ISSUE TITLE
Unit tests fail

### ISSUE THREAD

**Issue by jonathanherzog** [zama-ai/tfhe-rs#432]
Unit tests fail (main branch, fresh clone)

**To Reproduce**
1. Clone this repo
2. Confirm current branch is `main`
3. Install `nextest`
4. Run any of `integer-tests.sh`, `shortint-tests.sh`, or `cargo test`.

**Expected behaviour**
All unit tests are executed and pass.

**Evidence**
Output of `shortint-tests.sh` attached. Summary:

     `Summary [24289.015s] 459 tests run: 423 passed (95 slow, 1 flaky), 36 failed, 673 skipped`

Output of `integer-test.sh` attached. (Note: I hit ctrl-c after about 20 seconds). Summary:

     `Summary [  18.202s] 42/224 tests run: 22 passed, 20 failed, 1 skipped`

Output of `cargo-test` attached. (Note: I hit ctrl-c after about an hour). Failed tests:
```
test server_key::crt::tests::test_integer_smart_crt_mul_param_message_1_carry_1 ... FAILED
test server_key::crt::tests::test_integer_smart_crt_scalar_add_param_message_1_carry_1 ... FAILED
test server_key::crt::tests::test_integer_smart_crt_neg_param_message_1_carry_1 ... FAILED
test server_key::crt::tests::test_integer_smart_crt_add_param_message_1_carry_1 ... FAILED
test server_key::crt::tests::test_integer_smart_crt_sub_param_message_1_carry_1 ... FAILED
test server_key::crt::tests::test_integer_unchecked_crt_mul_param_message_1_carry_1 ... FAILED
test server_key::radix::tests::test_integer_smart_bitand_param_message_1_carry_1 ... FAILED
```

**Configuration(please complete the following information):**
 - OS: OsX 12.6
 - Rust: rustc 1.65.0 (897e37553 2022-11-02)
 - Cargo: cargo 1.65.0 (4bc8f24d3 2022-10-20)

Attachments:
* [integer-tests-output.txt](https://github.com/zama-ai/concrete/files/10032903/integer-tests-output.txt)
* [shortint-tests-output.txt](https://github.com/zama-ai/concrete/files/10032902/shortint-tests-output.txt)
* [cargo-test-output.txt](https://github.com/zama-ai/concrete/files/10033511/cargo-test-output.txt)

**Comment by jborfila** [comment]
Hey @jonathanherzog,
This is an issue from the old concrete that we are not able to reproduce on our side.
Is it solved on yours?

**Comment by jonathanherzog** [comment]
I haven't been ignoring you-- I've been trying to get the tests to pass. I no longer see errors, after updating to the latest code, but the tests run for a really long time and drain the battery on my laptop (even when it's plugged in). 

Given how old this ticket is, and that you can get the tests to pass on your end, it's fine with me if you close the ticket. If I run into problems again, I'll submit a new ticket.

Thanks.
