### ISSUE TITLE
Question: About performance

### ISSUE THREAD

**Issue by On0n0k1** [zama-ai/tfhe-rs#447]
Hello! Great work on this project.

I was benchmarking some of the operations with this crate, and found some interesting details.

 - Encrypting a new u64 takes around 300ms on my machine;
 - Decrypting a u64 takes on average 5 us;
 - Adding an encrypted u64 to another encrypted u64 costs around 5 us;
 - Adding an unencrypted u64 to an encrypted u64 is super fast. Around  50 ns;
 - Multiplying 2 encrypted u64 is taking around 700ms;
 - Multiplying an encrypted u64 with an unencrypted u64 takes around 330 ms;
 
 These numbers are not bad. I absolutely loved how efficient adding two encrypted numbers together can be.
 
 Do you have some tips on how to increase the performance of our tfhe runtime? Are optimizations coming in the future? Will we be able to reduce those numbers further?

**Comment by IceTDrinker** [comment]
hello @On0n0k1 

I don't think we benchmark encryption at this time so I cannot comment on the 300ms encryption time, though it feels a bit slow from afar

So for performance there are a few things you can do on your end at compile time.

Example command to run core crypto test:

```console
RUSTFLAGS="-C target-cpu=native" cargo +stable test --profile release \
        --features=x86_64-unix -p tfhe -- core_crypto::
```

setting RUSTFLAGS to target the native CPU will generate potentially non portable assembly but it will be the fastest possible assembly clang generates for your CPU

Don't forget the `--release` flag ! You can also tweak the release profile to use LTO (note that this currently does not work on Apple Silicon and we have a bug to file regarding that issue)

Example in a Cargo.toml:

```toml
[profile.release]
lto = "fat"
```

We have dedicated features for efficient CSPRNGs:
x86_64 (efficient x86 CSPRNG + rdseed seeder)
x86_64-unix (efficient x86 CSPRNG + rdseed seeder + /dev/random seeder fallback)
aarch64 (efficient arm CSPRNG)
aarch64-unix (efficient arm CSPRNG + /dev/random seeder fallback)

On x86 if you use a nightly toolchain you can enable avx512 primitives:
```console
RUSTFLAGS="-C target-cpu=native" cargo +nightly test --profile release \
        --features=x86_64-unix,nightly-avx512 -p tfhe -- core_crypto::
```

Let me know if it answers your questions :)

**Comment by On0n0k1** [comment]
Thank you. That was a lot of great information. Not sure if it should be reported as a bug, but I always use the release flag. When running it in debug mode it freezes for more than 30 seconds when generating new keys. I will try these configurations next.

Just one quick question. Are there any optimizations or features that you plan to bring in the coming months? Just so we can look forward to them as they arrive.

**Comment by IceTDrinker** [comment]
The next release will have big speed improvements if you were using the previousl 0.2.4 release.

As for the debug build, well it's just that the unoptimized build is super slow and is expected for any software, it's not really a bug 🙂 

If I have answered to your questions please close the issue :)

**Comment by On0n0k1** [comment]
Thank you. Have a nice day.
