### ISSUE TITLE
Execution time issue

### ISSUE THREAD

**Issue by vivekkumar15** [zama-ai/tfhe-rs#490]
**Describe the bug**
Example code in the repo takes around 165 seconds to execute on local

**To Reproduce**
I'm running the multiplication example of this repo after adding tfhe in cargo.toml of a sample project.
The example takes a total of around 165 seconds on my local and out of which 160 seconds are for the multiplication step.
Is this expected?

[dependencies]
tfhe = { version = "*", features = ["boolean", "shortint", "integer", "aarch64-unix"] }

**Configuration(please complete the following information):**
 Mac OS, M1

**Comment by tmontaigu** [comment]
make sure you compile with the `--release` flag.

**Comment by tmontaigu** [comment]
> All benchmarks were launched on an AWS m6i.metal with the following specifications: Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz and 512GB of RAM.

Yes this is expected, the machine where we run benchmarks has 128 cores all of which are used 100% during 256bits multiplication

**Comment by On0n0k1** [comment]
2 minutes is actually fast. You should see the size of the ciphers as well. Is there really a need for integers that can be as high as 2^256-1 for multiplication?
