### ISSUE TITLE
get_mut_checked and get_ref_unchecked should probably be marked `unsafe`

### ISSUE THREAD

**Issue by Manishearth** [zama-ai/tfhe-rs#526]
As far as I can tell this isn't externally reachable, however, ideally, these two APIs would be marked `unsafe` since they're usable throughout the crate and they dereference arbitrary pointers (so they have invariants).

https://github.com/zama-ai/tfhe-rs/blob/b92d6400f4a669ad2171049058f3bf58467507b7/tfhe/src/c_api/utils.rs#L28-L46

**Comment by IceTDrinker** [comment]
Fair point, though they would be accessible in the rest of the crate only if the "private" feature ˋ__c_apiˋ is enabled, it's not a big patch, will add that
