### ISSUE TITLE
pbs_modulus_switch question/suggestion

### ISSUE THREAD

**Issue by mvanbeirendonck** [zama-ai/tfhe-rs#589]
Hi,

I have a small suggestion for the function [pbs_modulus_switch](https://github.com/zama-ai/tfhe-rs/blob/37be7511888871b9adb62e3d141914f1048816c1/tfhe/src/core_crypto/fft_impl/common.rs#L17). I think the typical understanding is that this function returns a value mod `2N`, with `N` the `poly_size`. The `mod 2N` is missing in tfhe-rs, however, resulting in this function possibly returning values equal to exactly `2N`.

The `mod 2N` is not essential, because monomial multiplication with `0` or with `2N` is identical. But this misses a slight optimization opportunity. 

Related to this: in the blind rotation, there is the check `if *lwe_mask_element != Scalar::ZERO`, in which case the loop iteration is skipped. Isn't it possible and slightly better to check this after the mod-switch: `if monomial_degree != ZERO`? This is why I was thinking you would rather avoid the `2N` and have `0` instead.

Michiel

**Comment by IceTDrinker** [comment]
Hello @mvanbeirendonck the modulus switch is one of those things I haven't had a chance to dig deep into, with that said I believe you may be right here.

For the optimization you point out it would only on average trigger one time every 2N external products, or for our 2_2 parameters in shortint about once in 6 PBS (n = 742, 6* 742 = 4452 > 2N = 4096), as the masks of the LWE should be uniformly random from my understanding (let me know if my maths looks off here)

**Comment by IceTDrinker** [comment]
Thanks ! Will take a closer look (I like to take the time to understand a math primitive before modifying it, though what you say sounds perfectly reasonable 🙂 )

**Comment by IceTDrinker** [comment]
@mvanbeirendonck what's your usage of the mod switch ? In practice this is a "fast mod switch" which integrates well with the monomial multiplications we do right after (0 and 2N being equivalent as you pointed out), do you need a "proper" mod switch ?

**Comment by mvanbeirendonck** [comment]
Hi @IceTDrinker,

I see, so leaving out the reduction modulo 2N might be intentional? 

As you know, we work on hardware for TFHE. After mod-switching we expect the data to fit into `log2(2N)` bits, but this is currently not the case.

If the current implementation in `tfhe-rs` is more optimal this way, then this is a minor thing that we can easily account for on our end. I just wanted to let you know :-)

**Comment by IceTDrinker** [comment]
Yes in that case it saves a few operations (may not seem like much but once we do that ~1000 times for a PBS it may add up) and the result works for us :)

So yeah in that case I guess you may want to take it into account on your end, I'll keep this issue closed to update the pbs_modulus_switch function name and add a docstring to indicate this behavior that is not obvious !
