### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by woohyen0313** [zama-ai/tfhe-rs#730]
**Describe the bug**
if i wirte code fhe_int8_mul(mse, temp1, &temp1); 
As in the code below, if you perform an operation to multiply a variable by yourself, the memory remains and you can see that the memory is leaking.
So, when performing such operations, we declared new variables and continued to destroy them.

so we have to use variable temp and than destroy every time when we are coding like this(fhe_int8_mul(mse, temp1, &temp1); )
fhe_int8_mul(mse, temp1, &temp1);  -> fhe_int8_mul(mse, temp1, &temp2);  

so mul ,sub,add functions have to erase memory self when function is defined
**Configuration(please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]

**Comment by IceTDrinker** [comment]
Hello, @woohyen0313

Can you share a complete code example ?

It’s a bit surprising that memory is leaking, we’ll try to see what’s happening but for that we’ll need a code example 🙂

Cheers

**Comment by tmontaigu** [comment]
This is not something we can fix on our side `fhe_int8_mul` receives const pointers as input, so we cannot free them as it would require a mut pointer.

Also there are functions do to what you are trying, they have the work assign in them `fhe_int8_mul_assign` -> `fhe_int8_mul(temp1, mse);`

**Comment by woohyen0313** [comment]
fhe_int32_try_encrypt_with_public_key_i32(0, public_key, &minindex);
  time_t start_time = time(NULL);
  // Calculate MSE of i-number of usr and find minindex.
  for (int i = 0; i < 10000; i++) {
    if (i % 1000 == 0)
      fprintf(output, "mse loop:%d \n", i);

    fhe_int8_scalar_sub(first_hs, array[i][0], &square0);
    fhe_int8_mul(square0, square0, &square0);

    fhe_int8_scalar_sub(seconde_hs, array[i][1], &square1);
    fhe_int8_mul(square1, square1, &square1);

    fhe_int8_scalar_sub(third_hs, array[i][2], &square2);
    fhe_int8_mul(square2, square2, &square2);

    fhe_int8_add(square0, square1, &mse);
    fhe_int8_add(mse, square2, &mse);
    if (i == 0) {
      minmse = mse;
      continue;
    }

    // minmse update
    fhe_int8_gt(mse, minmse, &comp);
    fhe_int8_mul(minmse, comp, &temp0);
    fhe_int8_scalar_sub(comp, 1, &temp1);
    fhe_int8_mul(mse, temp1, &temp2);
    fhe_int8_sub(temp0, temp2, &minmse);

    fhe_int8_cast_into_fhe_int32(comp, &comp_32);

    // mimse index update
    fhe_int32_mul(minindex, comp_32, &temp0_32);
    fhe_int32_scalar_sub(comp_32, 1, &temp1_32);
    fhe_int32_scalar_mul(temp1_32, i, &temp2_32);
    fhe_int32_sub(temp0_32, temp2_32, &minindex);
    fhe_int8_gt(mse, minmse, &comp);

  }
this is example code if you run this code memory is increased

**Comment by IceTDrinker** [comment]
Hello @woohyen0313 as indicated by @tmontaigu above

> This is not something we can fix on our side `fhe_int8_mul` receives const pointers as input, so we cannot free them as it would require a mut pointer.
> 
> Also there are functions do to what you are trying, they have the word assign in them `fhe_int8_mul_assign` -> `fhe_int8_mul_assign(temp1, mse);`

the way you use the API at the moment is a misuse as a pointer is bot used as const pointer and a non const pointer, he indicates which API you can use to achieve what you want without memory leaks normally

**Comment by IceTDrinker** [comment]
hello @woohyen0313 did the proposer API help ?

**Comment by woohyen0313** [comment]
yes we write code just like that but we destroy every time.
I thought about changing the function so that if the same variable comes in, it can be handled through exception handling.

**Comment by IceTDrinker** [comment]
hello @woohyen0313 I think your question was answered and your usage of the C api was not correct, the API to do what you wanted was shared, we will be closing this issue, if you still have issues witht the original issue, feel free to re-open,

Cheers
