### ISSUE TITLE
Question: BSD3-clear patents

### ISSUE THREAD

**Issue by dfasg8329** [zama-ai/tfhe-rs#747]
Cool project! Wanted to ask which patents in this library are covered by BSD3-clear? Did you guys do some unique optimizations for TFHE?

**Comment by IceTDrinker** [comment]
hello @dfasg8329 as it was the end of year we did not get back to you right away 🙂 we will do so once we have an answer for you !

Cheers and happy new year !

**Comment by randhindi** [comment]
Hello! 

The original boolean version of TFHE is entirely open. Our work has been on the integer version and everything that comes from it.

Note that the license here allows you to use the code in anyway you want, and its free for personal use, research, prototyping etc, but if you plan on using it commercially you will need an additional license from us.

You can read more about our business model here: https://www.zama.ai/post/open-source

**Comment by IceTDrinker** [comment]
@dfasg8329 feel free to close this issue if your question was answered, if you still have questions related to your original questions ask them here, otherwise you can open other issues for different topics :)

**Comment by dfasg8329** [comment]
Thanks for the info, closing this :)

**Comment by randhindi** [comment]
The easiest is for you to search on google patent for Zama as the assignee, and you will see the ones that are already public. Note that we also have patents that were filed but not yet made public.

Are you asking in the context of commercial use? If so, lets chat offline as this is probably not the right channel for it :). You can reach me at rand@zama.ai

**Comment by IceTDrinker** [comment]
@dfasg8329 ok to close the issue and check on your end via email for the licensing information ?

**Comment by dfasg8329** [comment]
Thanks for the information guys, closing this for now :)
