### ISSUE TITLE
Some typo in the doc and whitepaper

### ISSUE THREAD

**Issue by 3for** [zama-ai/tfhe-rs#748]
In our [whitepaper](https://whitepaper.zama.ai/), page 7:
![屏幕快照 2023-12-26 下午8 48 50](https://github.com/zama-ai/tfhe-rs/assets/30716372/4b712c11-0757-458e-80dc-35040994e12c)
page 8:
![屏幕快照 2023-12-26 下午8 50 16](https://github.com/zama-ai/tfhe-rs/assets/30716372/357f5ee1-17b2-489c-82e8-3cd7d371810b)
 And in doc [What is TFHE-rs?](https://github.com/zama-ai/tfhe-rs/tree/main/tfhe/docs):
![屏幕快照 2023-12-26 下午8 53 09](https://github.com/zama-ai/tfhe-rs/assets/30716372/354bde88-3aaf-474e-ad48-239870e5effc)

**Comment by bcm-at-zama** [comment]
Thanks for reporting. @marcjoyezama @Pascal-Paillier , if you want to have a look, it's in your "Programmable Bootstrapping Enables Efficient Homomorphic Inference of Deep Neural Networks" CJP paper.

**Comment by IceTDrinker** [comment]
@3for thanks for the reports, bcm already pinged the relevant authors for the whitepaper, we'll take a look at the TFHE-rs doc issue you spotted

**Comment by IceTDrinker** [comment]
doc typo solved in https://github.com/zama-ai/tfhe-rs/pull/750

**Comment by Pascal-Paillier** [comment]
These are indeed typos in the paper, thanks for reporting them

**Comment by IceTDrinker** [comment]
hello @3for a revised version of the whitepaper has been published, the typography has changed so the content is not exactly in the same place as it used to be in the paper. The two typos you spotted are now fixed.

I will close this issue, if you see any other issue please open new issues !

Cheers
