### ISSUE TITLE
tfhe-rs 0.4.3 compilation conflict with x86_64-unix or shortint features

### ISSUE THREAD

**Issue by asraa** [zama-ai/tfhe-rs#931]
Hey! Seems like there's an issue with compiling tfhe-rs 0.4.x

**Describe the bug**
It seems like there's an issue with compiling tfhe-rs 0.4.3 with features that enable `next_tfhe` (for example, shortint).

This is because 0.4.3 requires bytemuck equal to `1.14.1`, while next_tfhe's 0.5.3 release requires bytemuch `^1.14.3`.

Here's the error:
```
# .---command stderr------------
# |     Updating crates.io index
# | error: failed to select a version for `bytemuck`.
# |     ... required by package `tfhe v0.5.3`
# |     ... which satisfies dependency `next_tfhe = "^0.5.0"` of package `tfhe v0.4.3`
# |     ... which satisfies dependency `tfhe = "^0.4.3"` of package `heir-tfhe-rust-integration-test v0.1.0 (/usr/local/google/home/asraa/.cache/bazel/_bazel_asraa/dd6a35b586d0a2d65a5a8939e7a649cf/sandbox/linux-sandbox/5882/execroot/heir/bazel-out/k8-dbg/bin/tests/tfhe_rust/end_to_end/test_add_one.mlir.test.runfiles/heir/tests/tfhe_rust/end_to_end)`
# | versions that meet the requirements `^1.14.3` are: 1.14.3
# | 
# | all possible versions conflict with previously selected packages.
# | 
# |   previously selected package `bytemuck v1.14.1`
# |     ... which satisfies dependency `bytemuck = "=1.14.1"` of package `tfhe v0.4.3`
# |     ... which satisfies dependency `tfhe = "^0.4.3"` of package `heir-tfhe-rust-integration-test v0.1.0 (/usr/local/google/home/asraa/.cache/bazel/_bazel_asraa/dd6a35b586d0a2d65a5a8939e7a649cf/sandbox/linux-sandbox/5882/execroot/heir/bazel-out/k8-dbg/bin/tests/tfhe_rust/end_to_end/test_add_one.mlir.test.runfiles/heir/tests/tfhe_rust/end_to_end)`
# | 
# | failed to select a version for `bytemuck` which could resolve this conflict
```

**To Reproduce**
Create a cargo project with the following dep:
```
tfhe = { version = "0.4.3", features = ["shortint", "x86_64-unix"] }
```

See also: https://github.com/google/heir/issues/469

**Comment by IceTDrinker** [comment]
we'll fix this ASAP

**Comment by IceTDrinker** [comment]
unfortunately nightly stuff is not included in semver breakage

**Comment by IceTDrinker** [comment]
that's very weird, the line:

```
shortint = ["dep:paste", "next_tfhe?/shortint"]
```

should prevent from enabling next_tfhe if it's not enabled with forward_compatibility, on another note it seems cargo compiles both dependencies independently 🤔 our forward compatibility tests passed, is it maybe a weird/corner case behavior of your build system @asraa ?

**Comment by IceTDrinker** [comment]
ah no the bug now triggers but it did not trigger in our CI 😵‍💫

**Comment by IceTDrinker** [comment]
Ok got it the 0.5.3 has the fix for the nightly breakage and so now the conflict happens

**Comment by asraa** [comment]
Hmmm weird, I actually don't really understand why `next_tfhe` is enabled when forward_compatibility is not in our build system. The only features we have enabled are x86_64-unix and shortint. I can't tell if maybe something weird is going on with my default features... but

```
$ cargo add tfhe@0.4.3 -F x
error: unrecognized feature for crate tfhe: x
disabled features:
    __c_api, __coverage, __profiling, __wasm_api, aarch64, aarch64-unix, boolean
    boolean-c-api, boolean-client-js-wasm-api, experimental
    experimental-force_fft_algo_dif4, forward_compatibility, generator_aarch64_aes
    high-level-c-api, high-level-client-js-wasm-api, integer
    integer-client-js-wasm-api, internal-keycache, nightly-avx512
    parallel-wasm-api, safe-deserialization, shortint-c-api
    shortint-client-js-wasm-api
enabled features:
    generator_x86_64_aesni, seeder_unix, seeder_x86_64_rdseed, shortint, x86_64
    x86_64-unix

```

**Comment by asraa** [comment]
Ah, I see. Yeah, it seems like it; https://users.rust-lang.org/t/ignore-feature-in-optional-dependency-to-avoid-transitive-dep-flag-conflict/45992

**Comment by IceTDrinker** [comment]
release likely tomorrow, we need to backport fixes caused by SIMD breakage in a nightly update of rust early february

**Comment by IceTDrinker** [comment]
CI in progress https://github.com/zama-ai/tfhe-rs/pull/932

**Comment by IceTDrinker** [comment]
0.4.4 is out, cheers

**Comment by IceTDrinker** [comment]
@sartimo can you please open a new issue with the version you are using and the Cargo.toml causing the issue ?

Thanks

**Comment by IceTDrinker** [comment]
@sartimo I don't know what the issue is but I can confirm that a new project with 

```toml
[package]
name = "bug_ver"
version = "0.1.0"
edition = "2021"

[dependencies]
tfhe = { version = "0.4.4", features = ["shortint", "x86_64-unix"] }
```

compiles just fine on my x86 machine, also we recommend you move to more recent version of TFHE-rs, 0.7 if you can as it's the most recent and has some new useful primitives for data versioning.

Cheers
