### ISSUE TITLE
The use of single-thread mode for TFHE-rs

### ISSUE THREAD

**Issue by xldeng-chn** [zama-ai/tfhe-rs#941]
Hi there,
How can I run my TFHE-rs program in single-thread mode? 

I have found the related discussion in the zama community ([link](https://community.zama.ai/t/how-to-force-single-thread-execution-with-c-api/925)), but the c-threading branch mentioned in the discussion is currently missing. 

I have also found a related API called "ThreadCount" ([link](https://docs.rs/tfhe/latest/tfhe/core_crypto/commons/parameters/struct.ThreadCount.html)), but I have no idea of how to use this.

I will really appreciate your reply.

**Comment by tmontaigu** [comment]
The branch mentionned has been merged into main and th example can be found here https://github.com/zama-ai/tfhe-rs/blob/main/tfhe/c_api_tests/test_high_level_threading.c

**Comment by IceTDrinker** [comment]
@xldeng-chn did that solve you issue ? If so you can mark this issue as solved :)

cheers

**Comment by xldeng-chn** [comment]
Thank you very much, I find that code snippet.
