### ISSUE TITLE
How can I implement batch or pack operations based on tfhe-rs ? 

### ISSUE THREAD

**Issue by qxzhou1010** [zama-ai/tfhe-rs#970]
How can I implement **batch** operations or, in other words, **pack** operations based on tfhe-rs, similar to the pack operations in **BFV**? This way, N pieces of data can be processed at once.

**Comment by IceTDrinker** [comment]
Hello @qxzhou1010 could you indicate what you are wanting to batch ?

If you need to run things in parallel you can use rayon, if you are looking for things in lower level primitives, then if you could explain in more details what you need then we might be able to help you more clearly 🙂 

Cheers

**Comment by qxzhou1010** [comment]
Thank you @IceTDrinker  for your quickly reply.  

I've gone through the documentation of tfhe-rs and found that almost all encryption and operations are for single integers or boolean data. My question is, **is it possible to encrypt a vector as a whole?** Then, perform some operations on the encrypted vector? For example, operations like addition, dot product, etc.

**Comment by IceTDrinker** [comment]
@qxzhou1010 closest thing I can think of is encrypting a list of plaintext in a GLWE ciphertext, note that we don't have many glwe primitives, so I'm not sure you can keyswitch and you definitely cannot bootstrap a GLWE ciphertext

**Comment by qxzhou1010** [comment]
Thank you for your reply again. I will continue to explore tfhe-rs in more depth.

**Comment by IceTDrinker** [comment]
feel free to close this issue @qxzhou1010 and open new ones if you have new questions !

Cheers

**Comment by IceTDrinker** [comment]
@qxzhou1010 if this question has been answered I will close the issue, if that's fine with you

**Comment by IceTDrinker** [comment]
Closing, if you have other questions/issues, please open new ones ! 🙂
